tap "anomalyco/tap"
tap "artemyurov/tomobar", "https://github.com/ArtemYurov/homebrew-tomobar"
tap "felixkratz/formulae", "https://github.com/FelixKratz/homebrew-formulae", trusted: true
tap "mongodb/brew", trusted: true
tap "mutagen-io/mutagen", trusted: true
tap "nikitabobko/tap"
brew "aichat"
brew "atuin"
brew "bat"
brew "cmake"
brew "cronboard"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "libtiff"
brew "git-delta"
brew "git-lfs"
brew "imagemagick"
brew "jq"
brew "lazygit"
brew "luarocks"
brew "micromamba"
brew "mise"
brew "node"
brew "mongosh"
brew "neovim"
brew "openjdk@17"
brew "pandoc"
brew "poppler"
brew "postgresql@14"
brew "resvg"
brew "ripgrep"
brew "ruby", link: false
brew "s3cmd"
brew "sbt"
brew "sesh"
brew "sevenzip"
brew "sheldon"
brew "starship"
brew "telnet"
brew "terminal-notifier"
brew "tmux"
brew "tmux-fingers"
brew "tree"
brew "uv"
brew "wget"
brew "worktrunk"
brew "yarn"
brew "yazi"
brew "zoxide"
brew "anomalyco/tap/opencode", trusted: true
brew "felixkratz/formulae/borders"
brew "mongodb/brew/mongodb-community"
brew "mutagen-io/mutagen/mutagen"
cask "nikitabobko/tap/aerospace", trusted: true
cask "chromium"
cask "claude"
cask "claude-code"
cask "codex"
cask "font-fira-code"
cask "font-jetbrains-mono"
cask "font-meslo-lg-nerd-font"
cask "font-symbols-only-nerd-font"
cask "gemini"
cask "ghostty"
cask "kindavim"
cask "mactex"
cask "artemyurov/tomobar/tomobar", trusted: true
cask "wispr-flow"
npm "@getpaseo/cli"
npm "corepack"
